I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 214, in script call
    call screen dungeon_command
  File "game/script.rpy", line 260, in script
    python: # Rounds code
  File "game/script.rpy", line 313, in <module>
    pc_target = random.choice(opposition)
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 214, in script call
    call screen dungeon_command
  File "game/script.rpy", line 260, in script
    python: # Rounds code
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 313, in <module>
    pc_target = random.choice(opposition)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/random.py", line 346, in choice
  File "E:\Ren Py\renpy-8.1.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Dungeons of Hundwick 0.14_Combat_Update
Fri Dec 29 22:39:54 2023
